export const INVOICE_REQUEST = "INVOICE_REQUEST";
export const INVOICE_SUCCESS = "INVOICE_SUCCESS";
export const INVOICE_FAIL = "INVOICE_FAIL";

export const ALL_INVOICES_REQUEST = "ALL_INVOICES_REQUEST";
export const ALL_INVOICES_SUCCESS = "ALL_INVOICES_SUCCESS";
export const ALL_INVOICES_FAIL = "ALL_INVOICES_FAIL";

export const RESET_INVOICE = "RESET_INVOICE";
