export const LOAN_REQUEST = "LOAN_REQUEST";
export const LOAN_SUCCESS = "LOAN_SUCCESS";
export const LOAN_FAIL = "LOAN_FAIL";

export const LOAN_PROFILE_REQUEST = "LOAN_PROFILE_REQUEST";
export const LOAN_PROFILE_SUCCESS = "LOAN_PROFILE_SUCCESS";
export const LOAN_PROFILE_FAIL = "LOAN_PROFILE_FAIL";

export const LOAN_PRODUCTS_REQUEST = "LOAN_PRODUCTS_REQUEST";
export const LOAN_PRODUCTS_SUCCESS = "LOAN_PRODUCTS_SUCCESS";
export const LOAN_PRODUCTS_FAIL = "LOAN_PRODUCTS_FAIL";

export const LOAN_PRODUCTS_ADD_REQUEST = "LOAN_PRODUCTS_ADD_REQUEST";
export const LOAN_PRODUCTS_ADD_SUCCESS = "LOAN_PRODUCTS_ADD_SUCCESS";
export const LOAN_PRODUCTS_ADD_FAIL = "LOAN_PRODUCTS_ADD_FAIL";

export const LOAN_PRODUCTS_REMOVE_REQUEST = "LOAN_PRODUCTS_REMOVE_REQUEST";
export const LOAN_PRODUCTS_REMOVE_SUCCESS = "LOAN_PRODUCTS_REMOVE_SUCCESS";
export const LOAN_PRODUCTS_REMOVE_FAIL = "LOAN_PRODUCTS_REMOVE_FAIL";

export const LOAN_PAYMENTS_REQUEST = "LOAN_PAYMENTS_REQUEST";
export const LOAN_PAYMENTS_SUCCESS = "LOAN_PAYMENTS_SUCCESS";
export const LOAN_PAYMENTS_FAIL = "LOAN_PAYMENTS_FAIL";

export const LOAN_PROFILE_EDIT_REQUEST = "LOAN_PROFILE_EDIT_REQUEST";
export const LOAN_PROFILE_EDIT_SUCCESS = "LOAN_EDIT_SUCCESS";
export const LOAN_PROFILE_EDIT_FAIL = "LOAN_PROFILE_EDIT_FAIL";

export const LOAN_PROFILE_DELETE_REQUEST = "LOAN_PROFILE_DELETE_REQUEST";
export const LOAN_PROFILE_DELETE_SUCCESS = "LOAN_PROFILE_DELETE_SUCCESS";
export const LOAN_PROFILE_DELETE_FAIL = "LOAN_PROFILE_DELETE_FAIL";

export const LOAN_PROFILE_ADD_REQUEST = "LOAN_PROFILE_ADD_REQUEST";
export const LOAN_PROFILE_ADD_SUCCESS = "LOAN_PROFILE_ADD_SUCCESS";
export const LOAN_PROFILE_ADD_FAIL = "LOAN_PROFILE_ADD_FAIL";

export const LOAN_PAYMENTS_ADD_REQUEST = "LOAN_PAYMENTS_ADD_REQUEST";
export const LOAN_PAYMENTS_ADD_SUCCESS = "LOAN_PAYMENTS_ADD_SUCCESS";
export const LOAN_PAYMENTS_ADD_FAIL = "LOAN_PAYMENTS_ADD_FAIL";

export const LOAN_PAYMENTS_REMOVE_REQUEST = "LOAN_PAYMENTS_REMOVE_REQUEST";
export const LOAN_PAYMENTS_REMOVE_SUCCESS = "LOAN_PAYMENTS_REMOVE_SUCCESS";

export const LOAN_PAYMENTS_REMOVE_FAIL = "LOAN_PAYMENTS_REMOVE_FAIL";

export const LOAN_RESET = "LOAN_RESET";
