export const SPENDINGS_REQUEST = "SPENDINGS_REQUEST";
export const SPENDINGS_SUCCESS = "SPENDINGS_SUCCESS";
export const SPENDINGS_FAIL = "SPENDINGS_FAIL";

export const ADD_SPENDING_REQUEST = "ADD_SPENDING_REQUEST";
export const ADD_SPENDING_SUCCESS = "ADD_SPENDING_SUCCESS";
export const ADD_SPENDING_FAIL = "ADD_SPENDING_FAIL";

export const REMOVE_SPENDING_REQUEST = "REMOVE_SPENDING_REQUEST";
export const REMOVE_SPENDING_SUCCESS = "REMOVE_SPENDING_SUCCESS";
export const REMOVE_SPENDING_FAIL = "REMOVE_SPENDING_FAIL";

export const RESET_SPENDING = "RESET_SPENDING";

export const SEL_SPEND = "SEL_SPEND";
